name: agvision
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cloud_firestore: null
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  firebase_auth: null
  firebase_core: null
  firebase_database: ^10.2.2
  firebase_storage: null
  flutter:
    sdk: flutter
  flutter_easyloading: null
  flutter_google_places_sdk: ^0.3.7
  flutter_screenutil: ^5.5.2
  flutter_svg: null
  freezed_annotation: null
  geocoding: null
  geolocator: null
  get: null
  get_storage: null
  google_fonts: 6.1.0
  http: ^1.2.0
  image_picker: ^1.0.8
  location: 5.0.0
  lottie: ^3.1.0
  permission_handler: ^11.3.1
  pin_code_text_field: null
  pretty_dio_logger: ^1.1.1
  retrofit: ^4.1.0
  webview_flutter: ^4.0.1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_gen_runner: null
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  flutter_svg_opt: ^0.0.1
  flutter_test:
    sdk: flutter
  freezed: null
  json_serializable: null
  retrofit_generator: ^8.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svgs/
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  flutter_lints: ^1.0.0
  #   - family: Trajan Proc:\Users\Mystical Coder\Documents\farmx-google-hack-main\MobileApp\assets
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
